[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.68.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production]
  command = ".netlify/command-production.sh"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.68.3"

[context.branch-deploy]
  command = "netlify/command-branch-deploy.sh"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.68.3"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"



