[build]
  HUGO_VERSION = "0.68.3"
  ALGOLIA_APP_ID = "NLO8K25GU4"
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production]
  command = "netlify/algolia-helper.sh && hugo"

[context.branch-deploy.environment]
  ALGOLIA_INDEX_NAME = "dev_kiroule"
  
[context.branch-deploy]
  command = "netlify/algolia-helper.sh && hugo -b $DEPLOY_PRIME_URL --buildFuture"

[context.deploy-preview.environment]
  
[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"



