[build]
  publish = "public"
  command = "hugo"

# URL: https://kiroule.com/
[context.production.environment]
  HUGO_VERSION = "0.72.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  # Algolia index name needed to run algolia/run-index-upload.sh
  ALGOLIA_INDEX_NAME = "prod_kiroule"

[context.production]
  command = "hugo --buildFuture && algolia/run-index-upload.sh -p"

# URL: https://dev--kiroule.netlify.app/
[context.dev.environment]
  HUGO_VERSION = "0.72.0"
  # Algolia index name needed to run algolia/run-index-upload.sh
  ALGOLIA_INDEX_NAME = "dev_kiroule"

[context.dev]
  command = "hugo --environment dev -b $DEPLOY_PRIME_URL --buildFuture --buildDrafts && algolia/run-index-upload.sh -p -u $DEPLOY_PRIME_URL"

# URL: https://toc-bug--kiroule.netlify.app/
[context.toc-bug.environment]
  HUGO_VERSION = "0.72.0"
  # Algolia index name needed to run algolia/run-index-upload.sh
  ALGOLIA_INDEX_NAME = "toc-bug_kiroule"

[context.toc-bug]
  command = "hugo --environment toc-bug -b $DEPLOY_PRIME_URL --buildFuture && algolia/run-index-upload.sh -p -u $DEPLOY_PRIME_URL"
